In [111]:
# Import libraries

import pandas as pd
import seaborn as sns
import numpy as np

import matplotlib
import matplotlib.pyplot as plt
plt.style.use('ggplot')
from matplotlib.pyplot import figure
import datetime as dt
from datetime import datetime

%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (12,8) # Adjusts the configuration of the plot we will create


# Read in the data

player_list = pd.read_excel('Case Study Football.xlsx', sheet_name='Player_List')
player_eval = pd.read_excel('Case Study Football.xlsx', sheet_name='Player_Evaluation_period')
physical_asst = pd.read_excel('Case Study Football.xlsx', sheet_name='physical_assessment_monthly')
match_stats = pd.read_excel('Case Study Football.xlsx', sheet_name='match_statistics_OverallSeason')
field_training = pd.read_excel('Case Study Football.xlsx', sheet_name='Field_trainings_OverallSeason')
gym_session = pd.read_excel('Case Study Football.xlsx', sheet_name='gym_trainings_OverallSeason')
str_test = pd.read_excel('Case Study Football.xlsx', sheet_name='strength_testing')
gps_data = pd.read_excel('Case Study Football.xlsx', sheet_name='GPS_MatchData')

In [112]:
player_list.head()

     Player_ID   YOB  Height Position     Position Name      Status
0  S202223P001  2004   163.7        W            Winger    Released
1  S202223P002  2004   169.0       AM   Attack-Midfield  Contracted
2  S202223P003  2004   166.5        W            Winger    Released
3  S202223P004  2004   177.6       CD   Central Defense  Contracted
4  S202223P005  2004   174.0       WD  Defensive Winger    Released

In [113]:
player_list.Status.unique()

array(['Released', 'Contracted', 'Active'], dtype=object)

In [114]:
player_list['Position Name'].unique()

array(['Winger', 'Attack-Midfield', 'Central Defense', 'Defensive Winger',
       'Defensive MIdfield', 'Striker', 'Goalkeeper'], dtype=object)

How are players being evaluated?

In [115]:
player_eval.head()

,Player_ID,assessment_period,assessment_date,overall_rating,overall_recommendation,no_matches,minutes_played,goals,assists,field_sessions,gym_sessions,field_presence,gym_presence
0,S202223P001,AP1,2022-12-31,3.0,Continue,2,60,0,0,23,3,0.92,1.0
1,S202223P002,AP1,2022-12-31,4.0,Continue,2,123,0,1,25,3,1.00,1.0
2,S202223P003,AP1,2022-12-31,4.0,Continue,2,90,1,0,25,3,1.00,1.0
3,S202223P004,AP1,2022-12-31,4.0,Continue,2,123,0,0,15,2,1.00,1.0
4,S202223P005,AP1,2022-12-31,2.0,Continue,2,149,0,0,25,3,1.00,1.0

In [140]:
player_eval['assessment_date'].unique()


# pd.to_datetime(player_eval['assessment_date']).dt.date

array(['2022-12-31T00:00:00.000000000', '2023-03-31T00:00:00.000000000',
       '2023-06-30T00:00:00.000000000'], dtype='datetime64[ns]')

Player Assesments keep occuring on a Quarterly basis, The earliest one in the dataset took place on the 31st of December, followed by one on the 31st of March, followed by the most recent one on the 30th of June.

In [13]:
physical_asst.head()

,Player_ID,Physical Assessment Period,Physical Assessment Date,Bodyweight (KG),Muscle (KG),Bodyfat (%)
0,S202223P001,PA-P0,2022-09-15,66.0,29.35,16.6
1,S202223P002,PA-P0,2022-09-15,67.6,31.09,12.0
2,S202223P003,PA-P0,2022-09-15,61.9,29.28,10.4
3,S202223P004,PA-P0,2022-09-15,76.5,39.07,10.7
4,S202223P005,PA-P0,2022-09-15,61.7,29.12,10.2

In [34]:
physical_asst['Physical Assessment Date'].unique()

array(['2022-09-15T00:00:00.000000000', '2022-10-15T00:00:00.000000000',
       '2022-11-15T00:00:00.000000000', '2022-12-15T00:00:00.000000000',
       '2023-01-15T00:00:00.000000000', '2023-02-15T00:00:00.000000000',
       '2023-03-15T00:00:00.000000000', '2023-05-15T00:00:00.000000000'],
      dtype='datetime64[ns]')

Physical Assesments occur every month on the 15th

In [14]:
match_stats.head()

,player_id,Games_played,Attendance,Yellow,Red,Yellow/Red,Goals,Assists
0,S202223P001,13,10,0,0,0,0,0
1,S202223P002,13,13,0,0,0,3,1
2,S202223P003,19,15,0,0,0,1,0
3,S202223P004,12,12,3,0,3,0,0
4,S202223P005,10,7,0,0,0,0,0

In [15]:
field_training.head()

     player_id  Sessions  Attendance  Missed    %
0  S202223P001        76          72       4   95
1  S202223P002        79          79       0  100
2  S202223P003       154         154       0  100
3  S202223P004        68          63       5   93
4  S202223P005        55          53       2   96

In [16]:
gym_session.head()

     player_id  Sessions  Attendance  Missed    %
0  S202223P001        11          11       0  100
1  S202223P002        14          14       0  100
2  S202223P003        27          27       0  100
3  S202223P004        11          11       0  100
4  S202223P005         8           8       0  100

In [17]:
str_test.head()

,player_id,Date,Weight,Reps,Benchpress 1rm,Pull up Reps,Jump Power,Weight2,Reps3,Squat 1rm
0,S202223P001,2022-09-20,40.0,6.0,46.451613,2.0,NaN,80.0,6.0,93.8
1,S202223P002,2022-09-20,50.0,5.0,56.250000,2.0,244.0,70.0,8.0,87.6
2,S202223P003,2022-09-30,50.0,1.0,50.000000,2.0,225.0,80.0,1.0,81.1
3,S202223P004,2022-09-20,50.0,4.0,54.545455,3.0,255.0,100.0,8.0,125.1
4,S202223P005,2022-09-30,65.0,4.0,70.909091,10.0,200.0,90.0,3.0,96.5

In [162]:
str_test['Date'].unique()

array(['2022-09-20T00:00:00.000000000', '2022-09-30T00:00:00.000000000',
       '2022-12-03T00:00:00.000000000'], dtype='datetime64[ns]')

In [18]:
gps_data.head()

,Season,Player ID,Session Date,Session Start Time,Session End Time,Drill Title,Drill Start Time,Drill End Time,Total Time,Accelerations,Average Metabolic Power,Average Speed,Distance Per Min,Distance Total,Explosive Distance,High Speed Running (Absolute),Energy Expenditure (KCal),Sprint Distance,Sprints
0,2022/2023,S202223P021,2022-10-03,19:02:00,20:50:00,Match Full Time,19:02:02,21:18:25,02:16:23,56,5.60,3.67,61.34,7641.48,809.55,360.92,797.94,437.42,27
1,2022/2023,S202223P008,2022-10-03,19:02:00,20:50:00,Match Full Time,19:02:10,21:20:26,02:18:17,82,8.17,5.33,88.89,11251.25,1102.23,834.92,1188.92,946.00,53
2,2022/2023,S202223P015,2022-10-03,19:02:00,20:50:00,Match Full Time,19:02:10,21:18:10,02:16:00,23,5.95,3.85,64.46,2842.97,350.80,162.35,301.32,208.33,10
3,2022/2023,S202223P044,2022-10-03,19:02:00,20:50:00,Match Full Time,19:02:40,21:16:06,02:13:26,63,6.39,4.21,70.28,8624.90,828.37,560.54,895.29,679.71,33
4,2022/2023,S202223P040,2022-10-03,19:02:00,20:50:00,Match Full Time,19:02:40,21:16:06,02:13:26,58,8.24,5.36,89.46,8631.06,803.31,659.52,916.91,796.53,45

In [163]:
gps_data['Session Date'].unique()

array(['2022-10-03T00:00:00.000000000', '2022-10-05T00:00:00.000000000',
       '2022-10-06T00:00:00.000000000', '2022-10-19T00:00:00.000000000',
       '2022-10-26T00:00:00.000000000', '2022-11-02T00:00:00.000000000',
       '2022-11-09T00:00:00.000000000', '2022-11-16T00:00:00.000000000',
       '2022-11-20T00:00:00.000000000', '2022-11-23T00:00:00.000000000',
       '2022-11-30T00:00:00.000000000', '2022-12-02T00:00:00.000000000',
       '2022-08-12T00:00:00.000000000', '2022-10-12T00:00:00.000000000',
       '2022-12-14T00:00:00.000000000'], dtype='datetime64[ns]')

In [151]:
AP1 = player_eval[player_eval['assessment_period'] == 'AP1']
player_eval[player_eval['assessment_period'] == 'AP1']

,Player_ID,assessment_period,assessment_date,overall_rating,overall_recommendation,no_matches,minutes_played,goals,assists,field_sessions,gym_sessions,field_presence,gym_presence
0,S202223P001,AP1,2022-12-31,3.0,Continue,2,60,0,0,23,3,0.9200,1.00
1,S202223P002,AP1,2022-12-31,4.0,Continue,2,123,0,1,25,3,1.0000,1.00
2,S202223P003,AP1,2022-12-31,4.0,Continue,2,90,1,0,25,3,1.0000,1.00
3,S202223P004,AP1,2022-12-31,4.0,Continue,2,123,0,0,15,2,1.0000,1.00
4,S202223P005,AP1,2022-12-31,2.0,Continue,2,149,0,0,25,3,1.0000,1.00
5,S202223P006,AP1,2022-12-31,2.0,Continue,2,43,0,0,24,3,0.9600,1.00
6,S202223P007,AP1,2022-12-31,5.0,Continue,2,138,1,0,25,3,1.0000,1.00
7,S202223P008,AP1,2022-12-31,5.0,Continue,2,93,1,0,8,2,1.0000,1.00
8,S202223P009,AP1,2022-12-31,4.0,Continue,2,100,1,0,25,3,1.0000,1.00
9,S202223P010,AP1,2022-12-31,4.0,Continue,2,90,0,0,17,2,1.0000,1.00
10,S202223P011,AP1,2022-12-31,3.0,Continue,2,80,0,0,14,2,1.0000,1.00
11,S202223P012,AP1,2022-12-31,3.0,Continue,2,90,0,0,14,2,1.0000,1.00
12,S202223P013,AP1,2022-12-31,2.0,Continue,2,42,0,0,15,2,1.0000,1.00
13,S202223P014,AP1,2022-12-31,3.0,Continue,2,75,0,0,21,3,0.8400,1.00
14,S202223P015,AP1,2022-12-31,3.0,Continue,2,135,0,0,25,3,1.0000,1.00
15,S202223P016,AP1,2022-12-31,5.0,Continue,2,123,0,0,25,3,1.0000,1.00
16,S202223P017,AP1,2022-12-31,3.0,Continue,2,115,0,1,13,2,1.0000,1.00
17,S202223P018,AP1,2022-12-31,3.0,Continue,2,105,0,0,15,2,1.0000,1.00
18,S202223P019,AP1,2022-12-31,5.0,Continue,1,45,0,0,6,2,1.0000,1.00
19,S202223P020,AP1,2022-12-31,4.0,Continue,2,42,0,0,15,2,1.0000,1.00
20,S202223P021,AP1,2022-12-31,5.0,Continue,2,123,1,0,25,3,1.0000,1.00
21,S202223P022,AP1,2022-12-31,5.0,Continue,2,93,0,0,8,2,1.0000,1.00
22,S202223P023,AP1,2022-12-31,4.0,Continue,2,130,0,1,18,2,1.0000,1.00
23,S202223P024,AP1,2022-12-31,3.0,Continue,2,42,0,0,18,2,1.0000,1.00
24,S202223P025,AP1,2022-12-31,4.0,Continue,2,135,0,0,18,2,1.0000,1.00
25,S202223P026,AP1,2022-12-31,4.0,Continue,2,105,0,0,17,2,1.0000,1.00
26,S202223P027,AP1,2022-12-31,3.0,Continue,2,72,0,0,17,2,1.0000,1.00
27,S202223P028,AP1,2022-12-31,3.0,Continue,2,42,0,0,18,2,1.0000,1.00
28,S202223P029,AP1,2022-12-31,4.0,Continue,2,72,0,0,16,2,0.9400,1.00
29,S202223P030,AP1,2022-12-31,3.0,Continue,2,90,0,0,17,2,1.0000,1.00
30,S202223P031,AP1,2022-12-31,4.0,Continue,0,0,0,0,9,2,0.5000,0.66
31,S202223P032,AP1,2022-12-31,3.0,Continue,1,9,0,0,12,2,0.6667,0.66
32,S202223P033,AP1,2022-12-31,3.0,Continue,2,67,0,0,17,2,1.0000,1.00
33,S202223P034,AP1,2022-12-31,4.0,Continue,0,0,0,0,1,1,1.0000,1.00
34,S202223P035,AP1,2022-12-31,4.0,Continue,2,90,0,0,15,2,1.0000,1.00
35,S202223P036,AP1,2022-12-31,2.0,Continue,2,90,0,0,18,2,1.0000,1.00
36,S202223P037,AP1,2022-12-31,3.0,Continue,2,90,0,0,18,2,1.0000,1.00
37,S202223P038,AP1,2022-12-31,3.0,Continue,2,65,0,0,18,2,1.0000,1.00
38,S202223P039,AP1,2022-12-31,3.0,Continue,1,45,0,0,18,2,1.0000,1.00
39,S202223P040,AP1,2022-12-31,5.0,Continue,2,123,0,0,18,2,1.0000,1.00
40,S202223P041,AP1,2022-12-31,3.0,Continue,2,90,0,0,10,2,1.0000,1.00
41,S202223P042,AP1,2022-12-31,3.0,Continue,1,15,0,0,17,2,1.0000,1.00
42,S202223P043,AP1,2022-12-31,3.0,Continue,2,50,1,0,18,2,1.0000,1.00
43,S202223P044,AP1,2022-12-31,5.0,Continue,2,123,0,0,18,2,1.0000,1.00
44,S202223P045,AP1,2022-12-31,4.0,Continue,2,90,0,0,18,2,1.0000,1.00
45,S202223P046,AP1,2022-12-31,3.0,Continue,1,45,0,0,12,2,0.6667,1.00

Observation: Everyone is given an overall recommendation of Continue, regardless of their overall rating. This could mean the First Assesment period is meant to allow the players to adapt to the academy so they may be judged more fairly from the next assessment onwards

In [147]:
player_eval[player_eval['assessment_period'] == 'AP2']

,Player_ID,assessment_period,assessment_date,overall_rating,overall_recommendation,no_matches,minutes_played,goals,assists,field_sessions,gym_sessions,field_presence,gym_presence
46,S202223P001,AP2,2023-03-31,3.0,Replace,13,158,0,0,76,11,0.95,1.00
47,S202223P002,AP2,2023-03-31,5.0,Continue,13,903,3,1,74,13,1.00,1.00
48,S202223P003,AP2,2023-03-31,3.0,Continue,14,205,1,0,74,14,1.00,1.00
49,S202223P004,AP2,2023-03-31,5.0,Continue,12,921,0,0,64,10,0.92,1.00
50,S202223P005,AP2,2023-03-31,2.0,Replace,8,239,0,0,55,8,0.96,1.00
51,S202223P006,AP2,2023-03-31,2.0,Replace,7,75,0,0,64,12,0.94,1.00
52,S202223P007,AP2,2023-03-31,5.0,Continue,11,904,1,0,74,10,0.91,1.00
53,S202223P008,AP2,2023-03-31,5.0,Continue,14,1016,2,0,57,12,1.00,1.00
54,S202223P009,AP2,2023-03-31,4.0,Continue,13,658,1,1,75,15,0.97,1.00
55,S202223P010,AP2,2023-03-31,4.0,Continue,15,650,0,0,66,14,0.89,1.00
56,S202223P011,AP2,2023-03-31,3.0,Continue,14,203,0,0,64,14,0.92,1.00
57,S202223P012,AP2,2023-03-31,2.0,Continue,13,180,0,0,63,14,0.95,1.00
58,S202223P013,AP2,2023-03-31,2.0,Replace,7,62,0,0,66,10,0.88,1.00
59,S202223P014,AP2,2023-03-31,3.0,Continue,14,278,0,0,76,14,0.93,1.00
60,S202223P015,AP2,2023-03-31,4.0,Continue,15,1035,0,1,74,15,1.00,1.00
61,S202223P016,AP2,2023-03-31,5.0,Continue,14,1131,0,0,74,13,1.00,1.00
62,S202223P017,AP2,2023-03-31,4.0,Continue,13,689,1,2,62,14,0.97,1.00
63,S202223P018,AP2,2023-03-31,5.0,Continue,12,766,6,0,64,11,0.95,1.00
64,S202223P019,AP2,2023-03-31,4.0,Continue,13,827,4,2,57,14,1.00,1.00
65,S202223P020,AP2,2023-03-31,4.0,Continue,13,821,0,0,66,12,0.94,1.00
66,S202223P021,AP2,2023-03-31,5.0,Replace,14,961,1,0,74,12,1.00,1.00
67,S202223P022,AP2,2023-03-31,5.0,Continue,14,1138,0,0,57,11,0.93,1.00
68,S202223P023,AP2,2023-03-31,5.0,Continue,15,771,0,1,69,14,0.97,1.00
69,S202223P024,AP2,2023-03-31,4.0,Continue,13,596,0,1,69,12,0.97,1.00
70,S202223P025,AP2,2023-03-31,4.0,Continue,15,560,0,0,69,14,0.94,1.00
71,S202223P026,AP2,2023-03-31,5.0,Replace,15,1189,4,3,68,14,0.97,1.00
72,S202223P027,AP2,2023-03-31,4.0,Continue,13,232,1,0,68,12,0.93,1.00
73,S202223P028,AP2,2023-03-31,4.0,Continue,13,303,0,0,69,12,0.97,1.00
74,S202223P029,AP2,2023-03-31,4.0,Continue,12,314,3,1,68,12,0.94,1.00
75,S202223P030,AP2,2023-03-31,4.0,Continue,11,708,0,0,67,14,0.94,1.00
76,S202223P031,AP2,2023-03-31,4.0,Continue,4,8,0,0,69,12,0.86,0.92
77,S202223P032,AP2,2023-03-31,3.0,Replace,1,9,0,0,68,14,0.82,0.86
78,S202223P033,AP2,2023-03-31,3.0,Continue,14,484,0,0,68,14,0.97,1.00
79,S202223P034,AP2,2023-03-31,3.0,Continue,11,468,0,0,52,11,0.94,1.00
80,S202223P035,AP2,2023-03-31,3.0,Continue,14,734,0,0,64,12,0.98,1.00
81,S202223P036,AP2,2023-03-31,3.0,Continue,14,900,0,0,68,9,1.00,1.00
82,S202223P037,AP2,2023-03-31,3.0,Continue,11,270,0,0,67,14,0.97,1.00
83,S202223P038,AP2,2023-03-31,3.0,Continue,13,335,0,0,69,14,0.94,1.00
84,S202223P039,AP2,2023-03-31,4.0,Continue,13,875,0,0,68,14,0.97,1.00
85,S202223P040,AP2,2023-03-31,5.0,Continue,14,1213,4,0,67,9,0.97,1.00
86,S202223P041,AP2,2023-03-31,4.0,Continue,14,1059,0,0,59,14,0.93,1.00
87,S202223P042,AP2,2023-03-31,3.0,Continue,12,82,0,0,68,11,0.97,1.00
88,S202223P043,AP2,2023-03-31,4.0,Continue,14,649,1,0,69,13,0.91,1.00
89,S202223P044,AP2,2023-03-31,5.0,Replace,13,1049,1,0,55,10,0.85,1.00
90,S202223P045,AP2,2023-03-31,2.0,Replace,7,127,0,0,60,7,0.97,1.00
91,S202223P046,AP2,2023-03-31,3.0,Continue,13,160,0,0,69,14,0.88,1.00

In [150]:
AP2 = player_eval[player_eval['assessment_period'] == 'AP2']

AP2[AP2['overall_recommendation'] == 'Replace']

,Player_ID,assessment_period,assessment_date,overall_rating,overall_recommendation,no_matches,minutes_played,goals,assists,field_sessions,gym_sessions,field_presence,gym_presence
46,S202223P001,AP2,2023-03-31,3.0,Replace,13,158,0,0,76,11,0.95,1.00
50,S202223P005,AP2,2023-03-31,2.0,Replace,8,239,0,0,55,8,0.96,1.00
51,S202223P006,AP2,2023-03-31,2.0,Replace,7,75,0,0,64,12,0.94,1.00
58,S202223P013,AP2,2023-03-31,2.0,Replace,7,62,0,0,66,10,0.88,1.00
66,S202223P021,AP2,2023-03-31,5.0,Replace,14,961,1,0,74,12,1.00,1.00
71,S202223P026,AP2,2023-03-31,5.0,Replace,15,1189,4,3,68,14,0.97,1.00
77,S202223P032,AP2,2023-03-31,3.0,Replace,1,9,0,0,68,14,0.82,0.86
89,S202223P044,AP2,2023-03-31,5.0,Replace,13,1049,1,0,55,10,0.85,1.00
90,S202223P045,AP2,2023-03-31,2.0,Replace,7,127,0,0,60,7,0.97,1.00

In [156]:
AP3 = player_eval[player_eval['assessment_period'] == 'AP3']

In [157]:
AP_1 = AP1[['Player_ID', 'assessment_period', 'assessment_date', 'overall_rating', 'overall_recommendation']]
AP_2 = AP2[['Player_ID', 'assessment_period', 'assessment_date', 'overall_rating', 'overall_recommendation']]
AP_3 = AP3[['Player_ID', 'assessment_period', 'assessment_date', 'overall_rating', 'overall_recommendation']]

In [170]:
merged_inner = pd.merge(AP_1, AP_2, on='Player_ID', how='inner')
merged_inner = pd.merge(merged_inner, AP_3, on='Player_ID', how='inner')

merged_inner = pd.merge(merged_inner, player_list[['Player_ID','Status']], on='Player_ID', how='inner')

In [171]:
merged_inner

,Player_ID,assessment_period_x,assessment_date_x,overall_rating_x,overall_recommendation_x,assessment_period_y,assessment_date_y,overall_rating_y,overall_recommendation_y,assessment_period,assessment_date,overall_rating,overall_recommendation,Status
0,S202223P001,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,3.0,Replace,AP3,2023-06-30,NaN,Replace,Released
1,S202223P002,AP1,2022-12-31,4.0,Continue,AP2,2023-03-31,5.0,Continue,AP3,2023-06-30,5.0,Continue,Contracted
2,S202223P003,AP1,2022-12-31,4.0,Continue,AP2,2023-03-31,3.0,Continue,AP3,2023-06-30,2.0,Replace,Released
3,S202223P004,AP1,2022-12-31,4.0,Continue,AP2,2023-03-31,5.0,Continue,AP3,2023-06-30,5.0,Continue,Contracted
4,S202223P005,AP1,2022-12-31,2.0,Continue,AP2,2023-03-31,2.0,Replace,AP3,2023-06-30,NaN,Replace,Released
5,S202223P006,AP1,2022-12-31,2.0,Continue,AP2,2023-03-31,2.0,Replace,AP3,2023-06-30,NaN,Replace,Released
6,S202223P007,AP1,2022-12-31,5.0,Continue,AP2,2023-03-31,5.0,Continue,AP3,2023-06-30,5.0,Continue,Contracted
7,S202223P008,AP1,2022-12-31,5.0,Continue,AP2,2023-03-31,5.0,Continue,AP3,2023-06-30,5.0,Continue,Contracted
8,S202223P009,AP1,2022-12-31,4.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,4.0,Continue,Contracted
9,S202223P010,AP1,2022-12-31,4.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,3.0,Replace,Active
10,S202223P011,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,3.0,Continue,AP3,2023-06-30,NaN,Replace,Released
11,S202223P012,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,2.0,Continue,AP3,2023-06-30,2.0,Replace,Active
12,S202223P013,AP1,2022-12-31,2.0,Continue,AP2,2023-03-31,2.0,Replace,AP3,2023-06-30,NaN,Replace,Released
13,S202223P014,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,3.0,Continue,AP3,2023-06-30,3.0,Replace,Active
14,S202223P015,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,3.0,Continue,Contracted
15,S202223P016,AP1,2022-12-31,5.0,Continue,AP2,2023-03-31,5.0,Continue,AP3,2023-06-30,5.0,Continue,Contracted
16,S202223P017,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,3.0,Replace,Active
17,S202223P018,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,5.0,Continue,AP3,2023-06-30,NaN,Replace,Released
18,S202223P019,AP1,2022-12-31,5.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,NaN,Replace,Released
19,S202223P020,AP1,2022-12-31,4.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,4.0,Replace,Active
20,S202223P021,AP1,2022-12-31,5.0,Continue,AP2,2023-03-31,5.0,Replace,AP3,2023-06-30,NaN,Replace,Released
21,S202223P022,AP1,2022-12-31,5.0,Continue,AP2,2023-03-31,5.0,Continue,AP3,2023-06-30,5.0,Continue,Contracted
22,S202223P023,AP1,2022-12-31,4.0,Continue,AP2,2023-03-31,5.0,Continue,AP3,2023-06-30,4.0,Replace,Active
23,S202223P024,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,3.0,Continue,Contracted
24,S202223P025,AP1,2022-12-31,4.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,4.0,Replace,Active
25,S202223P026,AP1,2022-12-31,4.0,Continue,AP2,2023-03-31,5.0,Replace,AP3,2023-06-30,NaN,Replace,Released
26,S202223P027,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,NaN,Replace,Released
27,S202223P028,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,3.0,Continue,Active
28,S202223P029,AP1,2022-12-31,4.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,NaN,Replace,Released
29,S202223P030,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,4.0,Continue,Active
30,S202223P031,AP1,2022-12-31,4.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,3.0,Replace,Active
31,S202223P032,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,3.0,Replace,AP3,2023-06-30,NaN,Replace,Released
32,S202223P033,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,3.0,Continue,AP3,2023-06-30,4.0,Replace,Active
33,S202223P034,AP1,2022-12-31,4.0,Continue,AP2,2023-03-31,3.0,Continue,AP3,2023-06-30,3.0,Replace,Active
34,S202223P035,AP1,2022-12-31,4.0,Continue,AP2,2023-03-31,3.0,Continue,AP3,2023-06-30,4.0,Continue,Contracted
35,S202223P036,AP1,2022-12-31,2.0,Continue,AP2,2023-03-31,3.0,Continue,AP3,2023-06-30,2.0,Replace,Released
36,S202223P037,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,3.0,Continue,AP3,2023-06-30,3.0,Replace,Active
37,S202223P038,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,3.0,Continue,AP3,2023-06-30,2.0,Replace,Released
38,S202223P039,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,3.0,Replace,Active
39,S202223P040,AP1,2022-12-31,5.0,Continue,AP2,2023-03-31,5.0,Continue,AP3,2023-06-30,5.0,Continue,Contracted
40,S202223P041,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,3.0,Replace,Active
41,S202223P042,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,3.0,Continue,AP3,2023-06-30,2.0,Replace,Released
42,S202223P043,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,4.0,Continue,AP3,2023-06-30,3.0,Replace,Active
43,S202223P044,AP1,2022-12-31,5.0,Continue,AP2,2023-03-31,5.0,Replace,AP3,2023-06-30,NaN,Replace,Released
44,S202223P045,AP1,2022-12-31,4.0,Continue,AP2,2023-03-31,2.0,Replace,AP3,2023-06-30,NaN,Replace,Released
45,S202223P046,AP1,2022-12-31,3.0,Continue,AP2,2023-03-31,3.0,Continue,AP3,2023-06-30,3.0,Replace,Active

In [169]:
player_list[['Player_ID','Status']]

      Player_ID      Status
0   S202223P001    Released
1   S202223P002  Contracted
2   S202223P003    Released
3   S202223P004  Contracted
4   S202223P005    Released
5   S202223P006    Released
6   S202223P007  Contracted
7   S202223P008  Contracted
8   S202223P009  Contracted
9   S202223P010      Active
10  S202223P011    Released
11  S202223P012      Active
12  S202223P013    Released
13  S202223P014      Active
14  S202223P015  Contracted
15  S202223P016  Contracted
16  S202223P017      Active
17  S202223P018    Released
18  S202223P019    Released
19  S202223P020      Active
20  S202223P021    Released
21  S202223P022  Contracted
22  S202223P023      Active
23  S202223P024  Contracted
24  S202223P025      Active
25  S202223P026    Released
26  S202223P027    Released
27  S202223P028      Active
28  S202223P029    Released
29  S202223P030      Active
30  S202223P031      Active
31  S202223P032    Released
32  S202223P033      Active
33  S202223P034      Active
34  S202223P035  Contracted
35  S202223P036    Released
36  S202223P037      Active
37  S202223P038    Released
38  S202223P039      Active
39  S202223P040  Contracted
40  S202223P041      Active
41  S202223P042    Released
42  S202223P043      Active
43  S202223P044    Released
44  S202223P045    Released
45  S202223P046      Active